### ISSUE TITLE
Resolve FB case

### ISSUE THREAD

**Issue by emgrig** [jozefizso/teamcity-fogbugz-notifier#1]
I'd like to know by any chances, this plugin will update/resolve a FobBugz case?
In terms of notifying FogBugz, is that mean resolve a case or doing something else? 
I have successfully used the other plugin for custom issue tracker. I'm hoping that this plugin will solve my another issue too:)

Thanks

**Comment by jozefizso** [comment]
I started this project so I could report build status from TeamCity to a custom FogBugz plugin. There was no intention automatically resolve FogBugz cases. I am not sure about the actual use case.

As the custom FogBugz plugin was developed internally and its development was stopped, I don't intend to work on this plugin for TeamCity.

**Comment by emgrig** [comment]
The use case is, that a developer doesn't need to go back to FogBugz and manually resolve a case.
Ideally TC will have a one more build step just resolving a FB case after a build successfully run.
Thanks for you response.
